### ISSUE TITLE
safer interpolation

### ISSUE THREAD

**Issue by goldingn** [njtierney/conmat#26]
in `predict_contacts()`, the contacts are predicted at integer resolution using the population age interpolator function to define population sizes, and then integrated to get the aggregate matrices. For some population age distributions, this predicts 0 population within the age bounds of the integration, which leads to non-finite prediction of contact rates. The integration range needs to be restricted to prevent this from happening during prediction.

**Comment by njtierney** [comment]
I believe this was resolved in https://github.com/njtierney/conmat/pull/27 - @goldingn is that correct?
