### ISSUE TITLE
mgcv::bam uses the offset as a covariate

### ISSUE THREAD

**Issue by goldingn** [njtierney/conmat#29]
😱😱😱😱

Only when specified in the formula, by the looks of it. This makes extrapolation behave in some very weird ways, e.g. places with more kids have far fewer school contacts.

Will investigate and can always pass in with the offset argument instead

**Comment by goldingn** [comment]
Oh hang on, I think that's because this is namespaced when it shouldn't be: https://github.com/njtierney/conmat/blob/master/R/fit_single_contact_model.R#L29
So am easy fix

**Comment by njtierney** [comment]
The old automatic namespacing strikes again!
