### ISSUE TITLE
Add Eyre weights as a data object

### ISSUE THREAD

**Issue by njtierney** [njtierney/conmat#44]
~~- [x] called `setting_weights` - for each of the settings (`home`, `school` , `work`, `other`)~~
~~- [ ] Provide `greta` code to reproduce these weights in `data-raw`~~
~~- [ ] Provide a function to appropriately map the weights to the transmission probability settings~~

**Comment by njtierney** [comment]
Priority 3

**Comment by njtierney** [comment]
Currently running into issues with greta 😱  but will add the other details soon

**Comment by njtierney** [comment]
@goldingn from memory we don't need to worry about the Eyre weights anymore, is that right?

**Comment by goldingn** [comment]
Correct. Eyre is superceded so we should remove it from the package.

**Comment by njtierney** [comment]
Looking at this PR: https://github.com/njtierney/conmat/commit/28c5fc882772ce4980eca5b03c8e398a5e6c5784

- [ ] Remove relevant `NEWS.md` bullets listed in above PR
- [ ] Remove `data_setting_weights.R`
- [ ] remove `read_eyre_setting_weights.R`
- [ ] run `document()`
