### ISSUE TITLE
Ensure all functions are added to the website

### ISSUE THREAD

**Issue by njtierney** [njtierney/conmat#70]
See https://github.com/njtierney/conmat/blob/master/_pkgdown.yml#L10-L57

We need to check that all the functions in the package appear in the lines above

**Comment by njtierney** [comment]
running `pkgdown::build_site()` should provide some warnings on functions that aren't listed in website

**Comment by njtierney** [comment]
See current action to see where it is failing: https://github.com/njtierney/conmat/actions/workflows/pkgdown.yaml

Might also need to update pkgdown YAML to the current version: https://github.com/r-lib/actions/blob/v2/examples/pkgdown.yaml

**Comment by aarathybabu97** [comment]
Resolved in [587d758](https://github.com/njtierney/conmat/commit/587d758229b3c3273a4514edff1be3ade4d11721) and [4bc1b06](https://github.com/njtierney/conmat/commit/4bc1b0629614ffa2c690837adc5473e1edb0966f)
