### ISSUE TITLE
Refactor `get_per_capita_household_size`

### ISSUE THREAD

**Issue by njtierney** [njtierney/conmat#98]
This function currently just works for ABS state and LGAs, it should instead implement the general per capita calculation

Then there can be specific ones for:

- ABS state
- ABS LGA

So, overall, three functions

1. `per_capita_household_size`
2. `abs_per_capita_household_size_lga`
3. `abs_per_capita_household_size_state`

`per_capita_household_size` essentially does https://github.com/njtierney/conmat/blob/master/R/get_per_capita_household_size.R#L87-L108 and would require arguments for:

- data
- household size (number of people in a household)
- population (in household)

Then `abs_per_capita_household_size_lga` and `abs_per_capita_household_size_state` would essentially implement the necessary parts of https://github.com/njtierney/conmat/blob/master/R/get_per_capita_household_size.R#L28-L86

**Comment by aarathybabu97** [comment]
```r

library(conmat)

# LGA specific 

demo_data <- abs_per_capita_household_size_lga(lga = "Albury (C)")

demo_data

#> # A tibble: 8 × 5
#> # Groups:   lga [1]
#>    year state lga        household_size n_people
#>   <dbl> <chr> <chr>               <dbl>    <dbl>
#> 1  2016 NSW   Albury (C)              1     6020
#> 2  2016 NSW   Albury (C)              2    13476
#> 3  2016 NSW   Albury (C)              3     8220
#> 4  2016 NSW   Albury (C)              4    10164
#> 5  2016 NSW   Albury (C)              5     5205
#> 6  2016 NSW   Albury (C)              6     1866
#> 7  2016 NSW   Albury (C)              7      392
#> 8  2016 NSW   Albury (C)              8      336


per_capita_household_size(household_data=demo_data,
                           household_size_col=household_size,
                           n_people_col=n_people)
#> [1] 3.085466


# Can pass multiple LGA / State. Happy  to remove that if it's unnecessary
state_demo_data <- abs_per_capita_household_size_state(state = c("NSW","TAS"))

library(conmat)


state_demo_data <- abs_per_capita_household_size_state(state = c("NSW","TAS"))

state_demo_data 

#> # A tibble: 1,288 × 5
#> # Groups:   state [2]
#>     year state lga                   household_size n_people
#>    <dbl> <chr> <chr>                          <dbl>    <dbl>
#>  1  2016 NSW   Albury (C)                         1     6020
#>  2  2016 NSW   Albury (C)                         2    13476
#>  3  2016 NSW   Albury (C)                         3     8220
#>  4  2016 NSW   Albury (C)                         4    10164
#>  5  2016 NSW   Albury (C)                         5     5205
#>  6  2016 NSW   Albury (C)                         6     1866
#>  7  2016 NSW   Albury (C)                         7      392
#>  8  2016 NSW   Albury (C)                         8      336
#>  9  2016 NSW   Armidale Regional (A)              1     2983
#> 10  2016 NSW   Armidale Regional (A)              2     7326
#> # … with 1,278 more rows

# User could then filter for the region as per their convenience 
per_capita_household_size(household_data=state_demo_data%>%
                            dplyr::filter(state=="NSW"),
                          household_size_col=household_size,
                          n_people_col=n_people)
#> [1] 3.4407
Created on 2022-10-13 by the reprex package (v2.0.1)
```

**Comment by njtierney** [comment]
Hi Aarathy, can you have a comparison of the old function as well, just so we can be sure that they are doing the same thing?

**Comment by njtierney** [comment]
I think we are missing the extra step where we wanted to run `per_capita_household_size` at the end of this? The output of this I don't think should be a data frame. We will also need to update other uses of `get_per_capita_household_size` in the `conmat` package.

**Comment by aarathybabu97** [comment]
@njtierney Oh yes! I was under the impression that the abs specific functions were supposed to just return the household distributions and then use `per_capita_household_size()` for retrieving the per capita household size. Now that I look at it I named the functions `abs_per_capita_household_size`, I'll add the rest of the computation as well. Thank you!
